//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JediContract", Namespace="http://schemas.datacontract.org/2004/07/WebService.Contract")]
    [System.SerializableAttribute()]
    public partial class JediContract : WebApplication.WebService.EntityContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSithField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSith {
            get {
                return this.IsSithField;
            }
            set {
                if ((this.IsSithField.Equals(value) != true)) {
                    this.IsSithField = value;
                    this.RaisePropertyChanged("IsSith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityContract", Namespace="http://schemas.datacontract.org/2004/07/WebService.Contract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication.WebService.JediContract))]
    public partial class EntityContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetJedis", ReplyAction="http://tempuri.org/IService/GetJedisResponse")]
        WebApplication.WebService.JediContract[] GetJedis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetJedis", ReplyAction="http://tempuri.org/IService/GetJedisResponse")]
        System.Threading.Tasks.Task<WebApplication.WebService.JediContract[]> GetJedisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddJedis", ReplyAction="http://tempuri.org/IService/AddJedisResponse")]
        WebApplication.WebService.JediContract AddJedis(WebApplication.WebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddJedis", ReplyAction="http://tempuri.org/IService/AddJedisResponse")]
        System.Threading.Tasks.Task<WebApplication.WebService.JediContract> AddJedisAsync(WebApplication.WebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateJedis", ReplyAction="http://tempuri.org/IService/UpdateJedisResponse")]
        void UpdateJedis(WebApplication.WebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateJedis", ReplyAction="http://tempuri.org/IService/UpdateJedisResponse")]
        System.Threading.Tasks.Task UpdateJedisAsync(WebApplication.WebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DelJedis", ReplyAction="http://tempuri.org/IService/DelJedisResponse")]
        void DelJedis(WebApplication.WebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DelJedis", ReplyAction="http://tempuri.org/IService/DelJedisResponse")]
        System.Threading.Tasks.Task DelJedisAsync(WebApplication.WebService.JediContract jedi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplication.WebService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplication.WebService.IService>, WebApplication.WebService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication.WebService.JediContract[] GetJedis() {
            return base.Channel.GetJedis();
        }
        
        public System.Threading.Tasks.Task<WebApplication.WebService.JediContract[]> GetJedisAsync() {
            return base.Channel.GetJedisAsync();
        }
        
        public WebApplication.WebService.JediContract AddJedis(WebApplication.WebService.JediContract jedi) {
            return base.Channel.AddJedis(jedi);
        }
        
        public System.Threading.Tasks.Task<WebApplication.WebService.JediContract> AddJedisAsync(WebApplication.WebService.JediContract jedi) {
            return base.Channel.AddJedisAsync(jedi);
        }
        
        public void UpdateJedis(WebApplication.WebService.JediContract jedi) {
            base.Channel.UpdateJedis(jedi);
        }
        
        public System.Threading.Tasks.Task UpdateJedisAsync(WebApplication.WebService.JediContract jedi) {
            return base.Channel.UpdateJedisAsync(jedi);
        }
        
        public void DelJedis(WebApplication.WebService.JediContract jedi) {
            base.Channel.DelJedis(jedi);
        }
        
        public System.Threading.Tasks.Task DelJedisAsync(WebApplication.WebService.JediContract jedi) {
            return base.Channel.DelJedisAsync(jedi);
        }
    }
}
