//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JediContract", Namespace="http://schemas.datacontract.org/2004/07/WebService.Contract")]
    [System.SerializableAttribute()]
    public partial class JediContract : WebApplication.Services.EntityContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSithField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSith {
            get {
                return this.IsSithField;
            }
            set {
                if ((this.IsSithField.Equals(value) != true)) {
                    this.IsSithField = value;
                    this.RaisePropertyChanged("IsSith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityContract", Namespace="http://schemas.datacontract.org/2004/07/WebService.Contract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication.Services.JediContract))]
    public partial class EntityContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IJediService")]
    public interface IJediService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/GetJedis", ReplyAction="http://tempuri.org/IJediService/GetJedisResponse")]
        WebApplication.Services.JediContract[] GetJedis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/GetJedis", ReplyAction="http://tempuri.org/IJediService/GetJedisResponse")]
        System.Threading.Tasks.Task<WebApplication.Services.JediContract[]> GetJedisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/AddJedis", ReplyAction="http://tempuri.org/IJediService/AddJedisResponse")]
        WebApplication.Services.JediContract AddJedis(WebApplication.Services.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/AddJedis", ReplyAction="http://tempuri.org/IJediService/AddJedisResponse")]
        System.Threading.Tasks.Task<WebApplication.Services.JediContract> AddJedisAsync(WebApplication.Services.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/UpdateJedis", ReplyAction="http://tempuri.org/IJediService/UpdateJedisResponse")]
        WebApplication.Services.JediContract UpdateJedis(WebApplication.Services.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/UpdateJedis", ReplyAction="http://tempuri.org/IJediService/UpdateJedisResponse")]
        System.Threading.Tasks.Task<WebApplication.Services.JediContract> UpdateJedisAsync(WebApplication.Services.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/DelJedis", ReplyAction="http://tempuri.org/IJediService/DelJedisResponse")]
        bool DelJedis(WebApplication.Services.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediService/DelJedis", ReplyAction="http://tempuri.org/IJediService/DelJedisResponse")]
        System.Threading.Tasks.Task<bool> DelJedisAsync(WebApplication.Services.JediContract jedi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJediServiceChannel : WebApplication.Services.IJediService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JediServiceClient : System.ServiceModel.ClientBase<WebApplication.Services.IJediService>, WebApplication.Services.IJediService {
        
        public JediServiceClient() {
        }
        
        public JediServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JediServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JediServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JediServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication.Services.JediContract[] GetJedis() {
            return base.Channel.GetJedis();
        }
        
        public System.Threading.Tasks.Task<WebApplication.Services.JediContract[]> GetJedisAsync() {
            return base.Channel.GetJedisAsync();
        }
        
        public WebApplication.Services.JediContract AddJedis(WebApplication.Services.JediContract jedi) {
            return base.Channel.AddJedis(jedi);
        }
        
        public System.Threading.Tasks.Task<WebApplication.Services.JediContract> AddJedisAsync(WebApplication.Services.JediContract jedi) {
            return base.Channel.AddJedisAsync(jedi);
        }
        
        public WebApplication.Services.JediContract UpdateJedis(WebApplication.Services.JediContract jedi) {
            return base.Channel.UpdateJedis(jedi);
        }
        
        public System.Threading.Tasks.Task<WebApplication.Services.JediContract> UpdateJedisAsync(WebApplication.Services.JediContract jedi) {
            return base.Channel.UpdateJedisAsync(jedi);
        }
        
        public bool DelJedis(WebApplication.Services.JediContract jedi) {
            return base.Channel.DelJedis(jedi);
        }
        
        public System.Threading.Tasks.Task<bool> DelJedisAsync(WebApplication.Services.JediContract jedi) {
            return base.Channel.DelJedisAsync(jedi);
        }
    }
}
